import {createLineItem, InvoiceLineItem} from "@/components/invoice/invoice-item-shared";


export const mockInvoiceItems: InvoiceLineItem[] = [
    createLineItem({
        id: "INV-ITEM-001",
        saleType: "Goods",
        productDescription: "Dell Latitude 5440 Laptop",
        hsCode: "84713000",
        uom: "PCS",
        quantity: 2,
        cost: 820,
        unitPrice: 950,
        discount: 50,
        sro: "SRO-2024-01",
        srNo: "SR-001",
    }),
    createLineItem({
        id: "INV-ITEM-002",
        saleType: "Goods",
        productDescription: "Logitech MX Master 3S Mouse",
        hsCode: "84716090",
        uom: "PCS",
        quantity: 5,
        cost: 65,
        unitPrice: 85,
        discount: 25,
        sro: "SRO-2024-01",
        srNo: "SR-002",
    }),
    createLineItem({
        id: "INV-ITEM-003",
        saleType: "Goods",
        productDescription: 'Samsung 27" 4K Monitor',
        hsCode: "85285200",
        uom: "PCS",
        quantity: 3,
        cost: 310,
        unitPrice: 375,
        discount: 30,
        sro: "SRO-2024-02",
        srNo: "SR-003",
    }),
    createLineItem({
        id: "INV-ITEM-004",
        saleType: "Services",
        productDescription: "Website UI/UX Design Services",
        hsCode: "99831100",
        uom: "HOUR",
        quantity: 20,
        cost: 25,
        unitPrice: 40,
        discount: 50,
        sro: "SRO-2024-03",
        srNo: "SR-004",
    }),
    createLineItem({
        id: "INV-ITEM-005",
        saleType: "Goods",
        productDescription: "USB-C 65W Fast Charger",
        hsCode: "85044090",
        uom: "PCS",
        quantity: 10,
        cost: 22,
        unitPrice: 32,
        discount: 20,
        sro: "SRO-2024-02",
        srNo: "SR-005",
    }),
    createLineItem({
        id: "INV-ITEM-006",
        saleType: "Goods",
        productDescription: "Wireless Mechanical Keyboard",
        hsCode: "84716020",
        uom: "PCS",
        quantity: 4,
        cost: 70,
        unitPrice: 110,
        discount: 20,
        sro: "SRO-2024-01",
        srNo: "SR-006",
    }),
    createLineItem({
        id: "INV-ITEM-007",
        saleType: "Services",
        productDescription: "Cloud Hosting & Maintenance",
        hsCode: "99831500",
        uom: "MONTH",
        quantity: 3,
        cost: 100,
        unitPrice: 150,
        discount: 0,
        sro: "SRO-2024-03",
        srNo: "SR-007",
    }),
    createLineItem({
        id: "INV-ITEM-008",
        saleType: "Goods",
        productDescription: "Cat6 Ethernet Network Cable",
        hsCode: "85444900",
        uom: "MTR",
        quantity: 100,
        cost: 1.2,
        unitPrice: 2,
        discount: 10,
        sro: "SRO-2024-02",
        srNo: "SR-008",
    }),
];